[versions]
androidx-activity-compose = "1.7.2"
androidx-core = "1.10.1"
androidx-test-ext-junit = "1.1.5"
androidx-test-espresso-core = "3.5.1"
androidx-compose-bom = "2023.05.01"
androidx-navigation-compose = "2.5.3"
junit = "4.13.2"
plugins-android = "8.2.0-alpha05"
plugins-kotlin = "1.8.21"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Convention dependencies
gradle-android = { group = "com.android.tools.build", name = "gradle", version.ref = "plugins-android" }
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "plugins-kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugins-android" }
android-library = { id = "com.android.library", version.ref = "plugins-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "plugins-kotlin" }

[bundles]
